"""The LLM Composer — invoked ONLY on a Gap Miner escape-region report.

IT IS NOT A FREE-RUNNING IDEA GENERATOR. One call per TICK, never per transaction. That single decision
is what keeps the loop laptop-runnable and cost-bounded, and it is also the correct division of labour:
the LLM composes PLANS because choosing which morpheme composition to try next given a plain-English
description of where the detector is weak is a COMBINATORIAL-SEMANTIC act. It is not required where the
task is NUMERIC OPTIMISATION UNDER FEEDBACK — that is what the bandit does, better and three orders of
magnitude more cheaply.

Literature: Chen & Liu, "Illuminating Heuristic Design: Language-Model-Driven Quality-Diversity
Evolution", IEEE TEVC 2026 — an LLM as the VARIATION OPERATOR inside a quality-diversity loop is a
recognised design, and the LLM belongs at the mutation step rather than in the inner evaluation loop.

PERMITTED OUTPUT: a six-slot grammar string, bandit arm parameters, and a list of expected observable
signatures that must resolve to fields in the canonical schema. Nothing else.

FORBIDDEN OUTPUT, enforced by `attack/dual_use_lint.py` which FAILS THE BUILD: vendor-named bypass
procedures, executable code, enumeration procedures, real BINs, PII, persuasive scam copy.

CACHED BY DEFAULT. Every prompt/response pair is content-hash keyed into `attack/cache/` and replayed
unless `--fresh` is passed. `LLM_MODE=cached` is the default and NEVER TOUCHES THE NETWORK — which is
simultaneously a determinism guarantee and a demo-safety guarantee, because a live call at a venue is a
single point of failure. If the key or the budget is exhausted, the loop runs from cache and the archive
stops growing: a DEGRADED run, not a broken one.

THE BLIND COMPOSER. `blind=True` constructs an instance with NO ACCESS TO DEFENDER FEEDBACK — a sealed
genome. Held-out-family campaigns are generated by it, because without that control "held-out family"
degrades into "family the attacker optimised against the same detector", which is a much weaker claim.
"""

from __future__ import annotations

import hashlib
import json
import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence

from attack.dual_use_lint import RejectLog, lint_record, utc_stamp
from core.paths import paths
from core.rng import stream
from grammar.composition import SLOT_ORDER, Composition, load_slots
from grammar.typecheck import load_typechecker
from sim.schema import CANONICAL_FIELDS

#: Hard request cap, enforced by a counter rather than by intention. The design commits to a capped
#: spend for the whole build; a counter is what makes that a fact.
DEFAULT_MAX_LIVE_CALLS = 250

MODE_CACHED = "cached"
MODE_LIVE = "live"
MODE_OFFLINE = "offline"


@dataclass
class ComposerProposal:
    """What the Composer is allowed to emit."""

    grammar_str: str
    stages: tuple[str, ...]
    expected_signatures: tuple[str, ...]
    arm: Mapping[str, Any] = field(default_factory=dict)
    rationale: str = ""
    #: Provenance: which escape region prompted it, and whether the instance was defender-blind.
    from_escape_region: str = ""
    blind_composer: bool = False
    source: str = "heuristic"          # "llm" | "heuristic" | "cache"

    def as_dict(self) -> dict[str, Any]:
        return {
            "grammar_str": self.grammar_str,
            "stages": list(self.stages),
            "expected_signatures": list(self.expected_signatures),
            "arm": dict(self.arm),
            "rationale": self.rationale,
            "from_escape_region": self.from_escape_region,
            "blind_composer": self.blind_composer,
            "source": self.source,
        }


@dataclass
class AdmissionVerdict:
    ok: bool
    reasons: tuple[str, ...] = ()

    def explain(self) -> str:
        return "admitted" if self.ok else "; ".join(self.reasons)


class Composer:
    """The plan-level variation operator.

    Three code paths, and which one ran is always recorded on the proposal:
      * `cache`     — a content-hash hit in attack/cache/. THE DEFAULT.
      * `llm`       — a live provider call. Opt-in, counted, capped.
      * `heuristic` — a deterministic, grammar-aware fallback that needs no network at all.

    The heuristic path is not a stub. It is what makes `make all` runnable on a machine with no API
    key, and it is what the offline replay bundle uses. It mutates toward the escape region using the
    region's named features and the grammar's own morpheme metadata, which is a weaker variation
    operator than an LLM and is labelled as such in the telemetry.
    """

    def __init__(
        self,
        *,
        mode: str | None = None,
        blind: bool = False,
        max_live_calls: int = DEFAULT_MAX_LIVE_CALLS,
        cache_dir: Path | None = None,
    ) -> None:
        self.mode = (mode or os.environ.get("LLM_MODE") or MODE_CACHED).lower()
        if self.mode not in (MODE_CACHED, MODE_LIVE, MODE_OFFLINE):
            raise ValueError(f"LLM_MODE must be one of cached|live|offline, got {self.mode!r}")
        self.blind = bool(blind)
        self.max_live_calls = int(max_live_calls)
        self.cache_dir = cache_dir or paths.composer_cache
        self.n_live_calls = 0
        self.n_cache_hits = 0
        self.n_heuristic = 0
        self.n_rejected_by_lint = 0
        self.reject_log = RejectLog().load()
        self.rng = stream("attack.composer")

    # ---- prompt / cache ---------------------------------------------------------------
    def _prompt(self, escape_region: str, cell_id: str, parent: str | None, signatures: Sequence[str]) -> str:
        """The prompt. Constrained so the model's job is COMPOSITION, not prose.

        The morpheme vocabularies are inlined so the model cannot invent a value: an invented morpheme
        would fail the type check anyway, but spending a call to discover that is waste.
        """
        vocab = load_slots()
        slots = "\n".join(f"  {s}: {', '.join(vocab.ids(s))}" for s in SLOT_ORDER)
        blind_note = (
            "You have NO access to detector feedback, scores, or model internals. Propose from the "
            "grammar and the region description alone."
            if self.blind
            else "You may use only the escape-region description below. You have no model internals."
        )
        return (
            "You are composing a payment-fraud ATTACK COMPOSITION for a DEFENSIVE red-team archive.\n"
            "\n"
            "OUTPUT FORMAT — JSON only, no prose outside it:\n"
            '  {"grammar_str": "ACCESS=.../TRUST=.../RAIL=.../EVASION=.../MONETISATION=.../LABEL=...",\n'
            '   "stages": ["..."], "expected_signatures": ["schema_field_name", ...],\n'
            '   "arm": {"amount_band": "...", "fan_out": 3}, "rationale": "one sentence"}\n"'
            "\n"
            "HARD CONSTRAINTS:\n"
            "  * Use ONLY the morpheme values listed below. Inventing one is a failure.\n"
            "  * `expected_signatures` must be FIELD NAMES from the canonical payment schema.\n"
            "  * Emit NO tradecraft, NO procedures, NO code, NO real identifiers, NO persuasive copy.\n"
            "    The unit of content is a kill-chain SHAPE and a set of OBSERVABLE SIGNATURES.\n"
            f"  * {blind_note}\n"
            "\n"
            f"MORPHEME VOCABULARIES:\n{slots}\n"
            "\n"
            f"TARGET ARCHIVE CELL: {cell_id}\n"
            f"PARENT COMPOSITION: {parent or '(none — cell is empty)'}\n"
            f"DETECTOR ESCAPE REGION (plain English, from the Gap Miner):\n  {escape_region}\n"
            f"SIGNATURES THE REGION IS EXPRESSED OVER: {', '.join(signatures) or '(none)'}\n"
        )

    def _cache_key(self, prompt: str) -> str:
        return hashlib.blake2b(prompt.encode("utf-8"), digest_size=16).hexdigest()

    def _cache_path(self, key: str) -> Path:
        return self.cache_dir / f"{key}.json"

    def _cache_read(self, key: str) -> dict[str, Any] | None:
        p = self._cache_path(key)
        if not p.exists():
            return None
        try:
            return json.loads(p.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            return None

    def _cache_write(self, key: str, prompt: str, response: dict[str, Any]) -> None:
        self.cache_dir.mkdir(parents=True, exist_ok=True)
        self._cache_path(key).write_text(
            json.dumps({"prompt": prompt, "response": response}, indent=2) + "\n",
            encoding="utf-8",
        )

    # ---- the live call ----------------------------------------------------------------
    def _call_live(self, prompt: str) -> dict[str, Any] | None:
        """One provider call. Counted and capped.

        Returns None on ANY failure — missing key, exhausted budget, network error, malformed JSON.
        The caller then falls back to the heuristic path, which is why the whole pipeline is runnable
        with no key at all. A live path that raised would make the loop network-dependent, which is
        exactly the venue risk the design refuses to carry.
        """
        if self.n_live_calls >= self.max_live_calls:
            return None
        api_key = os.environ.get("ANTHROPIC_API_KEY")
        if not api_key:
            return None
        try:
            import anthropic  # optional dependency, imported lazily
        except ImportError:
            return None
        try:
            client = anthropic.Anthropic(api_key=api_key)
            model = os.environ.get("VAJRA_LLM_MODEL", "claude-sonnet-5")
            msg = client.messages.create(
                model=model,
                max_tokens=800,
                temperature=0.7,
                messages=[{"role": "user", "content": prompt}],
            )
            self.n_live_calls += 1
            text = "".join(
                block.text for block in msg.content if getattr(block, "type", "") == "text"
            )
            start, end = text.find("{"), text.rfind("}")
            if start < 0 or end <= start:
                return None
            return json.loads(text[start : end + 1])
        except Exception:  # noqa: BLE001 — any provider failure degrades to the heuristic path
            return None

    # ---- the heuristic path ----------------------------------------------------------
    def _heuristic(
        self,
        escape_region: str,
        cell_id: str,
        parent: str | None,
        legal_for_cell: Sequence[str],
    ) -> dict[str, Any] | None:
        """A deterministic, grammar-aware variation operator that needs no network.

        It reads the escape region's named features, maps them to the EVASION morphemes whose declared
        signatures overlap, and prefers a type-legal composition for the target cell that uses one of
        them. That is a weaker operator than an LLM — it cannot invent a genuinely novel combination —
        and the telemetry labels every proposal from this path `heuristic` so a coverage figure is never
        read as an LLM result when it was not.
        """
        if not legal_for_cell:
            return None
        vocab = load_slots()
        region = (escape_region or "").lower()
        scored: list[tuple[int, str]] = []
        for cand in legal_for_cell:
            try:
                comp = Composition.parse(cand)
            except Exception:  # noqa: BLE001
                continue
            ev = vocab.get("EVASION", comp.EVASION)
            sigs = [str(s).lower() for s in (ev.get("signatures") or ())]
            overlap = sum(1 for s in sigs if s.replace("_", " ") in region or s in region)
            # Prefer a composition that differs from the parent, so the archive actually moves.
            novelty = 1 if (parent and cand != parent) else 0
            scored.append((overlap * 2 + novelty, cand))
        if not scored:
            return None
        scored.sort(key=lambda t: -t[0])
        top = [c for sc, c in scored if sc == scored[0][0]]
        pick = top[int(self.rng.integers(0, len(top)))]
        comp = Composition.parse(pick)
        return {
            "grammar_str": pick,
            "stages": list(_stages_for(comp)),
            "expected_signatures": list(comp.declared_signatures()[:6]),
            "arm": {
                "amount_band": str(self.rng.choice(["micro", "low", "mid", "high"])),
                "fan_out": int(self.rng.choice([1, 3, 8])),
            },
            "rationale": (
                "heuristic variation: selected a type-legal composition for the target cell whose "
                "EVASION morpheme's declared signatures overlap the escape region"
            ),
        }

    # ---- the public entry point -------------------------------------------------------
    def propose(
        self,
        *,
        escape_region: str,
        cell_id: str,
        parent_composition: str | None,
        region_signatures: Sequence[str],
        legal_for_cell: Sequence[str],
        stamped_at: str | None = None,
    ) -> tuple[ComposerProposal | None, AdmissionVerdict]:
        """Propose one composition, lint it, and type-check it.

        Returns `(proposal_or_None, verdict)`. A rejected proposal is RECORDED in the reject log, not
        discarded silently — the log is the evidence that the boundary was enforced.
        """
        prompt = self._prompt(escape_region, cell_id, parent_composition, region_signatures)
        key = self._cache_key(prompt)
        stamp = stamped_at or utc_stamp()
        source = "heuristic"

        raw: dict[str, Any] | None = None
        cached = self._cache_read(key)
        if cached is not None:
            raw = cached.get("response")
            source = "cache"
            self.n_cache_hits += 1
        elif self.mode == MODE_LIVE:
            raw = self._call_live(prompt)
            if raw is not None:
                source = "llm"
                self._cache_write(key, prompt, raw)

        if raw is None:
            raw = self._heuristic(escape_region, cell_id, parent_composition, legal_for_cell)
            source = "heuristic"
            self.n_heuristic += 1
            if raw is not None and self.mode != MODE_OFFLINE:
                # Cache the heuristic result too, so a replay is byte-identical regardless of which
                # path produced it.
                self._cache_write(key, prompt, raw)

        if raw is None:
            return None, AdmissionVerdict(False, ("no proposal could be produced for this cell",))

        # ---- the dual-use lint. A BUILD GATE. -----------------------------------------
        lint = lint_record(raw)
        self.reject_log.record(
            source=source,
            proposal_id=key[:12],
            result=lint,
            stamped_at=stamp,
            context={"cell_id": cell_id, "escape_region": escape_region[:160]},
        )
        if lint.rejected:
            self.n_rejected_by_lint += 1
            return None, AdmissionVerdict(False, (f"dual-use lint: {lint.explain()}",))

        proposal, verdict = self._admit(raw, escape_region, source)
        return proposal, verdict

    def _admit(
        self, raw: Mapping[str, Any], escape_region: str, source: str
    ) -> tuple[ComposerProposal | None, AdmissionVerdict]:
        """The archive admission gate: type-check, then SIGNATURE RESOLUTION.

        TYPE-CHECKING IS NOT COHERENCE. A composition can satisfy every constraint and still describe
        an attack no attacker would run, and an LLM under a diversity objective will produce exactly
        that. The remaining defence is the spot-audit in `make archive-report` with a >20%-incoherent
        tripwire — stated because this gate cannot catch it.
        """
        reasons: list[str] = []
        gs = str(raw.get("grammar_str", "")).strip()
        try:
            comp = Composition.parse(gs)
        except Exception as exc:  # noqa: BLE001
            return None, AdmissionVerdict(False, (f"not a parseable composition: {exc}",))

        tc = load_typechecker()
        verdict = tc.check(comp)
        if not verdict.ok:
            reasons.append(f"type check failed: {verdict.explain()}")

        sigs = tuple(str(s) for s in (raw.get("expected_signatures") or ()))
        # SIGNATURE RESOLUTION. A composition claiming a signature no observer can see is rejected
        # rather than archived. Resolves against the canonical schema OR the feature registry: a
        # derived feature is a legitimate observable as long as it is computed from fields the named
        # observer holds.
        from grammar.signatures import partition

        parts = partition(sigs)
        n_resolved = len(parts["schema"]) + len(parts["feature"])
        if parts["unknown"]:
            reasons.append(
                f"{len(parts['unknown'])} claimed signatures resolve to NOTHING: "
                f"{parts['unknown'][:5]}. Either they alias a column we compute, or they are "
                f"design-only and must be declared so in grammar/signatures.yaml."
            )
        if n_resolved < 3:
            reasons.append(
                f"only {n_resolved} RESOLVED observable signatures (design-only observables do not "
                f"count) — three is the archive's admission criterion, not a style preference"
            )
        unresolved = parts["unknown"] + parts["design_only"]

        if reasons:
            return None, AdmissionVerdict(False, tuple(reasons))

        return (
            ComposerProposal(
                grammar_str=str(comp),
                stages=tuple(str(x) for x in (raw.get("stages") or _stages_for(comp))),
                expected_signatures=tuple(s for s in sigs if s not in unresolved),
                arm=dict(raw.get("arm") or {}),
                rationale=str(raw.get("rationale", ""))[:400],
                from_escape_region=escape_region[:240],
                blind_composer=self.blind,
                source=source,
            ),
            AdmissionVerdict(True),
        )

    # ---- reporting -------------------------------------------------------------------
    def flush_reject_log(self) -> Path:
        return self.reject_log.save()

    def diagnostics(self) -> dict[str, Any]:
        return {
            "mode": self.mode,
            "blind_composer": self.blind,
            "n_live_calls": self.n_live_calls,
            "max_live_calls": self.max_live_calls,
            "n_cache_hits": self.n_cache_hits,
            "n_heuristic_fallbacks": self.n_heuristic,
            "n_rejected_by_dual_use_lint": self.n_rejected_by_lint,
            "reject_log": self.reject_log.summary(),
            "invocation_policy": (
                "ONE call per TICK, only on a Gap Miner escape-region report. Never per transaction: "
                "per-transaction adaptation is what the bandit does, better and three orders of "
                "magnitude more cheaply."
            ),
            "network_policy": (
                "LLM_MODE=cached is the DEFAULT and never touches the network. The demo path is "
                "offline. If the key or the budget is exhausted the loop runs from cache and the "
                "archive stops growing — a degraded run, not a broken one."
            ),
            "heuristic_note": (
                "Proposals sourced `heuristic` came from the deterministic grammar-aware fallback, "
                "which is a WEAKER variation operator than an LLM. Labelled so a coverage figure is "
                "never read as an LLM result when it was not."
            ),
        }


def _stages_for(comp: Composition) -> tuple[str, ...]:
    """Default stage list for a composition, from its admissible depth."""
    from grammar.cell_of import admissible_depths

    depths = admissible_depths(comp)
    d = min(depths) if depths else 2
    return ("recon", "establish", "extract", "cashout")[:max(1, min(int(d), 4))]
