"use client";
import { useEffect, useState } from "react";
import { getJSON } from "@/lib/api";
import { pct } from "@/lib/format";

// Screen 3 — FIDELITY. The provenance badge wall. F1 is the never-cut gate; F3/F5 failures ship VISIBLE.
export default function Fidelity() {
  const [d, setD] = useState<any>(null);
  const [err, setErr] = useState("");
  useEffect(() => { getJSON("/fidelity").then(setD).catch((e) => setErr(String(e))); }, []);
  if (err) return <div className="err">Could not load fidelity: {err}. Run <span className="mono">make fidelity</span>.</div>;
  if (!d) return <div className="sub">loading…</div>;
  if (d.error) return <div className="notice">{d.error}</div>;
  const f1 = d.f1 || {}; const prov = d.provenance || {};
  const asserts = d.f3_f5_f6?.assertions || []; const summ = d.f3_f5_f6?.summary || {};
  const fmtMeasured = (v: any) => {
    // A SKIPPED assertion arrives as JSON null (NaN does not survive serialisation), and raw floats
    // rendered as 0.09596555171209688 beside a tidy expectation like [0, 0.5] look unfinished.
    if (v === null || v === undefined || Number.isNaN(v)) return "n/a";
    if (typeof v !== "number") return String(v);
    return Math.abs(v) >= 1000 ? v.toLocaleString("en-IN") : v.toFixed(4);
  };
  const badge = (t: string) => <span className={`badge ${t.toLowerCase()}`}>{t}</span>;
  return (
    <div>
      <h1>Fidelity — a failing test, not a claim</h1>
      <div className={`notice ${f1.passed ? "honest" : ""}`}>
        <b>F1 invariant gate (never cut):</b> {f1.n_violations} violations across {f1.n_invariants} invariants.
        {f1.passed ? " PASSED." : " FAILED — no data ships."} A hand-written invariant is not gameable by gradient, only satisfiable or violated.
      </div>
      <p className="sub">
        Exactly {prov.counts_by_tier?.T1} conditionals carry T1 ({(prov.t1_conditionals||[]).join(", ")});
        {prov.counts_by_tier?.T2} are T2 and {prov.counts_by_tier?.T3} are T3. {prov.honest_admission}
      </p>
      <p className="sub">
        F3/F5/F6: pass-rate {pct(summ.pass_rate_of_checked)} with {summ.n_failed_shipped_visible} failures
        SHIPPED VISIBLE. A visible failing assertion proves the tests can fail.
      </p>
      <table>
        <thead><tr><th>id</th><th>tier</th><th>status</th><th>what it tests</th><th>measured</th><th>expectation</th></tr></thead>
        <tbody>
          {asserts.map((a: any) => (
            <tr key={a.id}>
              <td className="mono">{a.id}</td><td>{badge(a.tier)}</td>
              <td><span className={`badge ${a.status === "PASS" ? "pass" : a.status === "FAIL" ? "fail" : "skip"}`}>{a.status}</span></td>
              <td style={{ fontSize: 12 }}>{a.description}</td>
              <td className="mono">{fmtMeasured(a.measured)}</td>
              <td className="mono" style={{ fontSize: 11 }}>{a.expectation}</td>
            </tr>
          ))}
        </tbody>
      </table>
      <p className="sub">The full report with the discriminator chart is generated by <span className="mono">make fidelity</span> as reports/fidelity.html.</p>
    </div>
  );
}
